### ISSUE TITLE
read_hex needlessly opens input file twice

### ISSUE THREAD

**Issue by vapier** [flying-elephant/wacom_source#13]
`main` does:

```
    file_name = argv[1];
    fp = fopen(argv[1], "rb");
    cnt = read_hex(fp, file_name, flash_data, DATA_SIZE, &maxAddr);
```

and `read_hex` then does:

```
  fd = open(file_name, O_RDWR);
```

if you need the fd for the already opened file (ignoring the fact you just opened it for _writing_), just use `fileno(fp)` to get the existing one.

**Comment by flying-elephant** [comment]
I didn't know that function. Thank you for your advice.
