### ISSUE TITLE
respect CPPFLAGS when compiling

### ISSUE THREAD

**Issue by vapier** [flying-elephant/wacom_source#15]
since the `Makefile` has a rule which produces a program from a source file (rather than two rules to do source->obj and obj->program), the compilation line needs to also include `$(CPPFLAGS)` (the preprocessor flags).

`$(CC) $(CFLAGS) $(CPPFLAGS) $(LDFLAGS) $(WACOMTOOLSRC) -o $(PROGNAME)`

**Comment by flying-elephant** [comment]
I will keep it mind, thanks!
