### ISSUE TITLE
incorrect flag order

### ISSUE THREAD

**Issue by vapier** [flying-elephant/wacom_source#8]
the `Makefile` does:
`$(CC) $(WACOMTOOLSRC) $(WACOMTOOLOBJ) $(CCFLAGS) $(LDFLAGS) -o $(PROGNAME)`

the `$(CFLAGS) $(LDFLAGS)` must be before the objects, not after.  so it should be `$(CC) $(CFLAGS) $(LDFLAGS) .........`.

**Comment by flying-elephant** [comment]
Thank you! I will keep it mind.
