### ISSUE TITLE
misuse of the all target

### ISSUE THREAD

**Issue by vapier** [flying-elephant/wacom_source#9]
the Makefile sets up compile & link of `$(PROGNAME)` under the `all` target when really it should get its own.  also, there is no `$(WACOMTOOLOBJ)` variable anymore.

```
all: $(PROGNAME)
$(PROGNAME): $(WACOMTOOLSRC)
  ...do build here...
```

**Comment by flying-elephant** [comment]
Thanks, I changed it orderly and deleted unnecessary variable.
